# Generated by Django 5.1.5 on 2025-02-05 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0003_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
